---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-masa-age-gender-face-4w
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
#  1G: 393.55182419
  256M: 643.9415593100001
#  2G: 472.64636834
  4G: 368.53780722
#  512M: 417.98935261
  # 1G: 812.97
  # 1G: 1550.2
  2G: 1291
  1G: 1322
  512M: 1367
rho: [1]
# rho: [0.8]
memory-constraints: [512M, 1G, 2G]
# memory-constraints: [512M]
modes: [masa-e, bulk, deepeye]
#modes: [execprio]
# modes: [deepeye]
repetitions: 50
cmd-base: bin/Exp_poisson_arrival_rv_nf
build-folder: cmake-build-release