---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ./resources
output-path: ./analysis/experiments/poisson_arrivals/rv-nf-multi-facenet-rpi-1g-512m-exp
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
  256M: 643.9415593100001
  512M: 2322
  1G: 2321
  2G: 2330
  4G: 368.53780722
rho: [1]
memory-constraints: [1G, 512M]
modes: [execprio-inter, execprio, partial, bulk, deepeye, linear]
repetitions: 50
cmd-base: ./bin/Exp_poisson_arrival_rv_nf
build-folder: .